-- Apr 9, 2015 2:11:39 PM VET
-- STA - Definicion de entidad
UPDATE SPS_Column SET DefaultValue='N',Updated=TO_DATE('2015-04-09 14:11:39','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=1013264 WHERE SPS_Column_ID=54109
;

-- Apr 9, 2015 2:11:46 PM VET
-- STA - Definicion de entidad
UPDATE AD_Rule SET Script='CREATE TABLE FTA_TechnicalForm (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, Comments VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT ''CO'', DocStatus VARCHAR(2) DEFAULT ''DR'', DocumentNo VARCHAR(60) DEFAULT NULL , FTA_Farm_ID NUMERIC(10) DEFAULT NULL , FTA_TechnicalForm_ID NUMERIC(10) NOT NULL, GenerateOrder CHAR(1) DEFAULT ''N'', IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsApproved CHAR(1) DEFAULT ''N'' CHECK (IsApproved IN (''Y'',''N'')) NOT NULL, Processed CHAR(1) DEFAULT ''N'' CHECK (Processed IN (''Y'',''N'')) NOT NULL, SalesRep_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_TechnicalForm_Key PRIMARY KEY (FTA_TechnicalForm_ID))',Updated=TO_DATE('2015-04-09 14:11:46','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=1013264 WHERE AD_Rule_ID=50275
;

-- Apr 9, 2015 2:12:57 PM VET
-- STA - Definicion de entidad
UPDATE AD_Table SET AccessLevel='6',Updated=TO_DATE('2015-04-09 14:12:57','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=1013264 WHERE AD_Table_ID=53058
;

