-- Nov 12, 2014 9:21:54 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50266,TO_TIMESTAMP('2014-11-12 21:21:47','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Farm','Q','CREATE TABLE FTA_Farm (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Area NUMBER NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_BPartner_Location_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FarmType CHAR(1) NOT NULL, FrontierEast VARCHAR(255) DEFAULT NULL , FrontierNorth VARCHAR(255) DEFAULT NULL , FrontierSouth VARCHAR(255) DEFAULT NULL , FrontierWest VARCHAR(255) DEFAULT NULL , FTA_Farm_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) DEFAULT ''N'' CHECK (IsDefault IN (''Y'',''N'')), IsValid CHAR(1) CHECK (IsValid IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_Farm_Key PRIMARY KEY (FTA_Farm_ID))',TO_TIMESTAMP('2014-11-12 21:21:47','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_Farm')
;

-- Nov 12, 2014 9:21:54 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50266,Updated=TO_TIMESTAMP('2014-11-12 21:21:54','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50211
;

-- Nov 12, 2014 9:22:18 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50267,TO_TIMESTAMP('2014-11-12 21:22:17','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Farm Division','Q','CREATE TABLE FTA_FarmDivision (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Area NUMBER NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_FarmDivision_ID NUMERIC(10) NOT NULL, FTA_Farm_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_FarmDivision_Key PRIMARY KEY (FTA_FarmDivision_ID))',TO_TIMESTAMP('2014-11-12 21:22:17','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_FarmDivision')
;

-- Nov 12, 2014 9:22:18 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50267,Updated=TO_TIMESTAMP('2014-11-12 21:22:18','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50212
;

-- Nov 12, 2014 9:22:28 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50268,TO_TIMESTAMP('2014-11-12 21:22:23','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Farming','Q','CREATE TABLE FTA_Farming (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Area NUMBER NOT NULL, Category_ID NUMERIC(10) NOT NULL, C_OrderLine_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EffectiveArea NUMBER DEFAULT NULL , EstimatedDate TIMESTAMP DEFAULT NULL , EstimatedQty NUMBER DEFAULT NULL , EstimatedYield NUMBER DEFAULT NULL , FarmingValidate CHAR(1) DEFAULT NULL , FinancingType CHAR(1) NOT NULL, FTA_FarmDivision_ID NUMERIC(10) NOT NULL, FTA_FarmerCredit_ID NUMERIC(10) DEFAULT NULL , FTA_Farming_ID NUMERIC(10) NOT NULL, GuideGenerate CHAR(1) DEFAULT NULL , HarvestEndDate TIMESTAMP DEFAULT NULL , HarvestStartDate TIMESTAMP DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsValid CHAR(1) DEFAULT NULL  CHECK (IsValid IN (''Y'',''N'')), MaxQty NUMBER DEFAULT NULL , PlantingCycle_ID NUMERIC(10) NOT NULL, PlantingEndDate TIMESTAMP DEFAULT NULL , PlantingStartDate TIMESTAMP DEFAULT NULL , Qty NUMBER DEFAULT NULL , Re_EstimatedQty NUMBER DEFAULT NULL , StartDate TIMESTAMP NOT NULL, Status CHAR(1) DEFAULT ''M'' NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_Farming_Key PRIMARY KEY (FTA_Farming_ID))',TO_TIMESTAMP('2014-11-12 21:22:23','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_Farming')
;

-- Nov 12, 2014 9:22:29 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50268,Updated=TO_TIMESTAMP('2014-11-12 21:22:29','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50213
;

-- Nov 12, 2014 9:22:38 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50269,TO_TIMESTAMP('2014-11-12 21:22:37','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Farming Stage','Q','CREATE TABLE FTA_FarmingStage (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Category_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DayFrom NUMBER NOT NULL, DayTo NUMBER NOT NULL, FTA_FarmingStage_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , SeqNo NUMBERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) DEFAULT NULL , CONSTRAINT FTA_FarmingStage_Key PRIMARY KEY (FTA_FarmingStage_ID))',TO_TIMESTAMP('2014-11-12 21:22:37','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_FarmingStage')
;

-- Nov 12, 2014 9:22:38 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50269,Updated=TO_TIMESTAMP('2014-11-12 21:22:38','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50214
;

-- Nov 12, 2014 9:22:43 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50270,TO_TIMESTAMP('2014-11-12 21:22:41','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Suggested Product','Q','CREATE TABLE FTA_SuggestedProduct (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Category_ID NUMERIC(10) DEFAULT NULL , Comments VARCHAR(255) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DayFrom NUMBER DEFAULT NULL , DayTo NUMBER DEFAULT NULL , Dosage_Uom_ID NUMERIC(10) DEFAULT NULL , FTA_FarmingStage_ID NUMERIC(10) DEFAULT NULL , FTA_ObservationType_ID NUMERIC(10) DEFAULT NULL , FTA_SuggestedProduct_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, M_Product_Category_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) NOT NULL, QtyDosage NUMBER DEFAULT NULL , SeqNo NUMBERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_SuggestedProduct_Key PRIMARY KEY (FTA_SuggestedProduct_ID))',TO_TIMESTAMP('2014-11-12 21:22:41','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_SuggestedProduct')
;

-- Nov 12, 2014 9:22:43 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50270,Updated=TO_TIMESTAMP('2014-11-12 21:22:43','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50215
;

-- Nov 12, 2014 9:22:46 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50271,TO_TIMESTAMP('2014-11-12 21:22:45','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Observation Type','Q','CREATE TABLE FTA_ObservationType (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_ObservationType_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT FTA_ObservationType_Key PRIMARY KEY (FTA_ObservationType_ID))',TO_TIMESTAMP('2014-11-12 21:22:45','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_ObservationType')
;

-- Nov 12, 2014 9:22:46 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50271,Updated=TO_TIMESTAMP('2014-11-12 21:22:46','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50216
;

-- Nov 12, 2014 9:22:50 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50272,TO_TIMESTAMP('2014-11-12 21:22:49','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Credit/Loan','Q','CREATE TABLE FTA_FarmerCredit (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMBER NOT NULL, AmtFarming NUMBER DEFAULT NULL , ApprovedAmt NUMBER DEFAULT NULL , ApprovedQty NUMBER DEFAULT NULL , BasedOnEffectiveQuantity CHAR(1) DEFAULT NULL  CHECK (BasedOnEffectiveQuantity IN (''Y'',''N'')), Beneficiary_ID NUMERIC(10) DEFAULT NULL , C_BPartner_ID NUMERIC(10) NOT NULL, C_Charge_ID NUMERIC(10) DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, C_PaymentTerm_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CreditType CHAR(1) NOT NULL, C_UOM_ID NUMERIC(10) DEFAULT NULL , DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT ''CO'' NOT NULL, DocStatus VARCHAR(2) DEFAULT ''DR'' NOT NULL, DocumentNo VARCHAR(60) DEFAULT NULL , EffectiveQty NUMBER DEFAULT NULL , FarmingAlloc CHAR(1) DEFAULT NULL , FTA_CreditAct_ID NUMERIC(10) DEFAULT NULL , FTA_CreditDefinition_ID NUMERIC(10) DEFAULT NULL , FTA_FarmerCredit_ID NUMERIC(10) NOT NULL, GenerateBillOfEx CHAR(1) DEFAULT NULL , GenerateOrder CHAR(1) DEFAULT ''N'', IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN (''Y'',''N'')) NOT NULL, IsBillOfExchangeDocBased CHAR(1) DEFAULT ''N'' CHECK (IsBillOfExchangeDocBased IN (''Y'',''N'')), IsManagesPaymentProgram CHAR(1) DEFAULT ''N'' CHECK (IsManagesPaymentProgram IN (''Y'',''N'')), IsManual CHAR(1) DEFAULT ''N'' CHECK (IsManual IN (''Y'',''N'')), IsPayScheduleValid CHAR(1) DEFAULT ''N'' CHECK (IsPayScheduleValid IN (''Y'',''N'')), M_Product_ID NUMERIC(10) DEFAULT NULL , Parent_FarmerCredit_ID NUMERIC(10) DEFAULT NULL , PreviousAmt NUMBER DEFAULT NULL , PreviousApprovedAmt NUMBER DEFAULT 0, PreviousApprovedQty NUMBER DEFAULT 0, PreviousQty NUMBER DEFAULT NULL , Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN (''Y'',''N'')), Processing CHAR(1) DEFAULT NULL , Qty NUMBER NOT NULL, QtyFarming NUMBER DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_FarmerCredit_Key PRIMARY KEY (FTA_FarmerCredit_ID))',TO_TIMESTAMP('2014-11-12 21:22:49','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_FarmerCredit')
;

-- Nov 12, 2014 9:22:50 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50272,Updated=TO_TIMESTAMP('2014-11-12 21:22:50','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50217
;

-- Nov 12, 2014 9:22:54 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50273,TO_TIMESTAMP('2014-11-12 21:22:53','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Credit Definition','Q','CREATE TABLE FTA_CreditDefinition (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMBER NOT NULL, C_DocTypeClosedAP_ID NUMERIC(10) DEFAULT NULL , C_DocTypeClosedAR_ID NUMERIC(10) DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, CopyFrom CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CreditType CHAR(1) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT ''CO'' NOT NULL, DocStatus VARCHAR(2) DEFAULT ''DR'' NOT NULL, DocumentNo VARCHAR(60) DEFAULT NULL , FTA_CreditDefinition_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN (''Y'',''N'')) NOT NULL, M_PriceList_ID NUMERIC(10) NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN (''Y'',''N'')), Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CreditDefinition_Key PRIMARY KEY (FTA_CreditDefinition_ID))',TO_TIMESTAMP('2014-11-12 21:22:53','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_CreditDefinition')
;

-- Nov 12, 2014 9:22:54 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50273,Updated=TO_TIMESTAMP('2014-11-12 21:22:54','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50218
;

-- Nov 12, 2014 9:22:58 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50274,TO_TIMESTAMP('2014-11-12 21:22:56','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Credit Definition Line','Q','CREATE TABLE FTA_CreditDefinitionLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMBER NOT NULL, C_Charge_ID NUMERIC(10) DEFAULT NULL , C_ChargeType_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_CDL_Category_ID NUMERIC(10) NOT NULL, FTA_CreditDefinition_ID NUMERIC(10) NOT NULL, FTA_CreditDefinitionLine_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDistributionLine CHAR(1) DEFAULT ''N'' CHECK (IsDistributionLine IN (''Y'',''N'')), IsExceedCreditLimit CHAR(1) DEFAULT ''N'' CHECK (IsExceedCreditLimit IN (''Y'',''N'')), Line NUMBERIC(10) NOT NULL, M_Product_Category_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) DEFAULT NULL , Price NUMBER NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN (''Y'',''N'')), Qty NUMBER DEFAULT 1 NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CreditDefinitionLine_Key PRIMARY KEY (FTA_CreditDefinitionLine_ID))',TO_TIMESTAMP('2014-11-12 21:22:56','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_CreditDefinitionLine')
;

-- Nov 12, 2014 9:22:58 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50274,Updated=TO_TIMESTAMP('2014-11-12 21:22:58','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50219
;

-- Nov 12, 2014 9:23:08 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50275,TO_TIMESTAMP('2014-11-12 21:23:02','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Technical Form','Q','CREATE TABLE FTA_TechnicalForm (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, Comments VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT ''CO'', DocStatus VARCHAR(2) DEFAULT ''DR'', DocumentNo VARCHAR(60) DEFAULT NULL , FTA_Farm_ID NUMERIC(10) DEFAULT NULL , FTA_TechnicalForm_ID NUMERIC(10) NOT NULL, GenerateOrder CHAR(1) DEFAULT ''N'', IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsApproved CHAR(1) DEFAULT ''N'' CHECK (IsApproved IN (''Y'',''N'')) NOT NULL, Processed CHAR(1) CHECK (Processed IN (''Y'',''N'')) NOT NULL, SalesRep_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_TechnicalForm_Key PRIMARY KEY (FTA_TechnicalForm_ID))',TO_TIMESTAMP('2014-11-12 21:23:02','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_TechnicalForm')
;

-- Nov 12, 2014 9:23:08 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50275,Updated=TO_TIMESTAMP('2014-11-12 21:23:08','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50220
;

-- Nov 12, 2014 9:23:11 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50276,TO_TIMESTAMP('2014-11-12 21:23:10','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Technical Form Line','Q','CREATE TABLE FTA_TechnicalFormLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Comments VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_FarmDivision_ID NUMERIC(10) NOT NULL, FTA_Farm_ID NUMERIC(10) NOT NULL, FTA_Farming_ID NUMERIC(10) NOT NULL, FTA_FarmingStage_ID NUMERIC(10) NOT NULL, FTA_ObservationType_ID NUMERIC(10) NOT NULL, FTA_TechnicalForm_ID NUMERIC(10) NOT NULL, FTA_TechnicalFormLine_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN (''Y'',''N'')), Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_TechnicalFormLine_Key PRIMARY KEY (FTA_TechnicalFormLine_ID))',TO_TIMESTAMP('2014-11-12 21:23:10','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_TechnicalFormLine')
;

-- Nov 12, 2014 9:23:11 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50276,Updated=TO_TIMESTAMP('2014-11-12 21:23:11','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50221
;

-- Nov 12, 2014 9:23:15 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50277,TO_TIMESTAMP('2014-11-12 21:23:15','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Products To Apply','Q','CREATE TABLE FTA_ProductsToApply (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, DateFrom TIMESTAMP DEFAULT NULL , DateTo TIMESTAMP DEFAULT NULL , Dosage_Uom_ID NUMERIC(10) NOT NULL, FTA_ProductsToApply_ID NUMERIC(10) NOT NULL, FTA_TechnicalForm_ID NUMERIC(10) NOT NULL, FTA_TechnicalFormLine_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsApplied CHAR(1) DEFAULT ''N'' CHECK (IsApplied IN (''Y'',''N'')), M_Product_ID NUMERIC(10) NOT NULL, M_Warehouse_ID NUMERIC(10) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN (''Y'',''N'')), Qty NUMBER NOT NULL, QtyDosage NUMBER NOT NULL, QtySuggested NUMBER DEFAULT NULL , Suggested_Uom_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_ProductsToApply_Key PRIMARY KEY (FTA_ProductsToApply_ID))',TO_TIMESTAMP('2014-11-12 21:23:15','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_ProductsToApply')
;

-- Nov 12, 2014 9:23:15 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50277,Updated=TO_TIMESTAMP('2014-11-12 21:23:15','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50222
;

-- Nov 12, 2014 9:23:20 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50278,TO_TIMESTAMP('2014-11-12 21:23:19','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Lot','Q','CREATE TABLE M_Lot (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateFrom TIMESTAMP DEFAULT NULL , DateTo TIMESTAMP DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, M_LotCtl_ID NUMERIC(10) DEFAULT NULL , M_Lot_ID NUMERIC(10) NOT NULL, M_Product_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT M_Lot_Key PRIMARY KEY (M_Lot_ID))',TO_TIMESTAMP('2014-11-12 21:23:19','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_M_Lot')
;

-- Nov 12, 2014 9:23:20 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50278,Updated=TO_TIMESTAMP('2014-11-12 21:23:20','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50223
;

-- Nov 12, 2014 9:23:25 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50279,TO_TIMESTAMP('2014-11-12 21:23:24','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Farmer Credit Fact','Q','CREATE TABLE FTA_Fact (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Table_ID NUMERIC(10) NOT NULL, Amt NUMBER NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_CreditDefinition_ID NUMERIC(10) NOT NULL, FTA_CreditDefinitionLine_ID NUMERIC(10) NOT NULL, FTA_Fact_ID NUMERIC(10) NOT NULL, FTA_FarmerCredit_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCreditFactManual CHAR(1) DEFAULT NULL  CHECK (IsCreditFactManual IN (''Y'',''N'')), Line_ID NUMERIC(10) DEFAULT NULL , Multiplier NUMBER DEFAULT NULL , Record_ID NUMBERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_Fact_Key PRIMARY KEY (FTA_Fact_ID))',TO_TIMESTAMP('2014-11-12 21:23:24','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_Fact')
;

-- Nov 12, 2014 9:23:25 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50279,Updated=TO_TIMESTAMP('2014-11-12 21:23:25','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50295
;

-- Nov 12, 2014 9:23:28 PM VET
-- SPS FTA
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50280,TO_TIMESTAMP('2014-11-12 21:23:27','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Account Statement','Q','CREATE TABLE FTA_RV_AccountStatement (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Table_ID NUMERIC(10) DEFAULT NULL , Amt NUMBER DEFAULT NULL , AmtAcctCr NUMBER DEFAULT NULL , AmtAcctDr NUMBER DEFAULT NULL , Balance NUMBER DEFAULT NULL , C_BPartner_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , FTA_CreditDefinition_ID NUMERIC(10) DEFAULT NULL , FTA_FarmerCredit_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL)',TO_TIMESTAMP('2014-11-12 21:23:27','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_FTA_RV_AccountStatement')
;

-- Nov 12, 2014 9:23:28 PM VET
-- SPS FTA
UPDATE SPS_Table SET AD_Rule_ID=50280,Updated=TO_TIMESTAMP('2014-11-12 21:23:28','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50296
;

